[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pyseq"
dynamic = ["version"]
description = "Compressed File Sequence String Module"
readme = "README.md"
requires-python = ">=3.8"
license = { text = "BSD-3-Clause" }
keywords = [
  "animation",
  "file sequence",
  "image sequence",
  "pipeline",
  "post-production",
  "pyseq",
  "visual effects",
  "vfx",
]
classifiers = [
  "Development Status :: 5 - Production/Stable",
  "Intended Audience :: Developers",
  "License :: OSI Approved :: BSD License",
  "Operating System :: OS Independent",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Topic :: Multimedia :: Graphics",
  "Topic :: Software Development :: Libraries :: Python Modules",
  "Topic :: Utilities",
]
authors = [
  { name = "Ryan Galloway", email = "ryan@rsgalloway.com" },
]
optional-dependencies = { dev = ["pytest", "flake8==7.1.1", "mccabe==0.7.0", "isort==5.13.2", "black==26.3.1"], test = ["pytest"] }

[tool.isort]
profile = "black"
line_length = 100
skip_gitignore = true

[tool.black]
line-length = 100
target-version = ["py38"]

[project.scripts]
lss = "pyseq.lss:main"
scopy = "pyseq.scopy:main"
sdiff = "pyseq.sdiff:main"
sfind = "pyseq.sfind:main"
smv = "pyseq.smove:main"
srm = "pyseq.sremove:main"
sstat = "pyseq.sstat:main"
stree = "pyseq.stree:main"

[project.urls]
Homepage = "https://github.com/rsgalloway/pyseq"
Documentation = "https://github.com/rsgalloway/pyseq/tree/main/docs"
Repository = "https://github.com/rsgalloway/pyseq"
Issues = "https://github.com/rsgalloway/pyseq/issues"

[tool.setuptools]
zip-safe = false

[tool.setuptools.package-dir]
"" = "lib"

[tool.setuptools.packages.find]
where = ["lib"]

[tool.setuptools.dynamic]
version = { attr = "pyseq.__version__" }
